### ISSUE TITLE
No display after upload 

### ISSUE THREAD

**Issue by Ralphy140** [madpilot/AmberDisplay#1]
Hi Madpilot, 

I am able to compile the sketch after adding in the required packages but i am not getting any display(nothing is ever displayed and no back light), I have a few T1 boards that I know work as they work fine with the ESPHome st7789v display driver for other projects i have built, I can also see the buttons working in the serial monitor when i press it shows the output of the options cycling through. 

I am not sure how to start debugging the display driver, I am 100% sure that I have the right board selected but i did have to add the TFT_eSPI library for it to compile I am not sure if thats expected or if it is supposed to be bundled with the esp board package that was downloaded with the board manager. 

Sorry for the lack of logs or as they all look fine and happy to take any sugestions 

Thanks 

Ralphy

**Comment by madpilot** [comment]
Try this version of TFT_eSPI: https://github.com/Xinyuan-LilyGO/TTGO-T-Display.

There is basic instructions on that page.

**Comment by Ralphy140** [comment]
Yep thats solve it!
